yourssu/YDS-iOS

YDS-Sample/AtomSampleViewController/BadgePageViewController.swift, YDS-Sample/PageListViewController.swift, YDS-iOS.xcodeproj/project.pbxproj, YDS-iOS/Source/Atom/YDSBadge.swift, YDS-iOS/Source/Foundation/YDSBasicColor.swift, YDS-iOS/Source/Foundation/YDSItemColor.swift, YDS-iOS/Source/Foundation/YDSSemanticColor.swift
Badge와 샘플 페이지를 만들었습니다.
**- YDS-iOS/Source/Atom/YDSBadge.swift**
뱃지를 구현했습니다.
**- YDS-Sample/AtomSampleViewController/BadgePageViewController.swift**
뱃지 샘플 페이지입니다.
**- YDS-iOS/Source/Foundation/YDSBasicColor.swift**
파일 명에 YDS라는 접두사를 붙였습니다.
BasicColor 앞에 YDS라는 접두사를 붙였습니다.
**- YDS-iOS/Source/Foundation/YDSSemanticColor.swift**
파일 명에 YDS라는 접두사를 붙였습니다.
**- YDS-iOS/Source/Foundation/YDSItemColor.swift**
[스펙](https://www.notion.so/yourssu/ItemColor-dev-2001aa5c234542859a1d0e97b62ec474)
Tag, Badge 등 Item에 사용되는 Color Enum입니다.
https://user-images.githubusercontent.com/54972653/127744544-853197c5-7e66-4bc2-b13f-28c4e7897580.mov
text == nil 일 때와 text == "" 일 때는 다른 결과가 나타납니다.
text == nil 일 때는 label 자체가 hidden 되지만
text == "" 일 때는 label이 hidden 되지 않고, 이로 인해 stackView의 spacing만큼 우측에 여백이 생깁니다.
이는 의도한 …
=> [Feature/YDS-44] Badge 구현 및 샘플 페이지 작성

YDS/Source/Atom/YDSProfileImageView.swift, YDS/Source/Foundation/YDSFont.swift, YDS/Source/Foundation/YDSSemanticColor.swift, YDS/Source/Foundation/YDSTypoStyle.swift
단순 수치 변경 및 추가입니다
커뮤니티 개발 전 준비 단계입니다
디자이너의 변덕
- 이슈 티켓 : https://github.com/yourssu/YDS-iOS/issues/94
파일 단위로 보지 마시고 커밋 단위로 보시면 됩니다!
=> [Feature/YDS-94] 커뮤니티를 위한 수치 변경 및 추가 

YDS-Storybook/PageListViewController.swift
Sample 앱 우상단의 버튼 변경
누르면 버전 정보가 나옵니다
=> [Feature/YDS-98-2] Version Button 추가

.swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata, YDS/Source/Component/TopBar/YDSNavigationController.swift
1. YDSNavigationController에 파라미터 없는 Init을 추가하였습니다.
2. pushViewController시 animation 여부를 설정할 수 있게 수정하였습니다.
3. setViewControllers로 View들을 설정했을 때에도 대비할 수 있게 하였습니다.
1. 코디네이터 패턴과 맞지 않게 rootViewController를 생성해서 넣어줘야하는 문제점이 있어서 변경하였습니다.
2. pushViewController시 animation이 없어야 하는 부분이 있어서 변경하였습니다.
- 이슈 티켓 : #106 
- 피그마 : 
- 관련 문서 : 
```Swift
let nvc = YDSNavigationController
override func start() {
let viewController = ViewController
nvc.pushViewController(viewController, animated: true) // 1. 먼저 pushViewController로 root를 지정해줍니다.
nvc.title = "회원가입"                                   // 2. 그 후에 title을 설정하면 적용됩니다.
nvc.modalPresentationStyle = .fullScreen
navigationController.present(nvc, animated: true)
}
```
setViewControllers도 마찬가지로 적용됩니다.
=> [Fix/#106] YDSNavigationController init 추가 및 animation 변수 설정

YDS-Storybook/AtomSampleViewController/EmojiButtonPageViewController.swift, YDS-Storybook/PageListViewController.swift, YDS.xcodeproj/project.pbxproj, YDS/Source/Atom/YDSEmojiButton.swift
이모지 버튼을 추가했습니다.
Button 작성된것과 유사하게 작성했어요.
Button의 기능과는 좀 멀어보여서 (isSelected가 중점) UIControl로 구현했습니다.
- 이슈 티켓 : #119 
- 피그마 : https://www.figma.com/file/0u52cd50xDQqjanMpUvUOM/%5B1.-iOS%5D-Yourssu-Design-System?node-id=3923%3A2232
- 관련 문서 : https://www.notion.so/yourssu/a8798e507a0349079feddc025dd5e4e9
=> [#119] 이모지 버튼 추가

.swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata, Package.resolved, Package.swift, YDS.xcodeproj/project.pbxproj, YDS.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
YDSTabBar가 scrollable일 때 좌우 여백 16을 추가했습니다
원래 있는 스펙인데 제가 피그마에서 놓쳤습니다
- 이슈 티켓 : #141 
- 피그마 : [링크](https://www.figma.com/file/0u52cd50xDQqjanMpUvUOM/%5B1.-iOS%5D-Yourssu-Design-System?node-id=4899%3A3931)
[Parchment 수정 코드](https://github.com/yourssu/Parchment/commit/42036be5d011c83145e9f8e2705c7d3756e46607)
- 조건에 따라 상단의 `menuInsets`의 값을 다르게 했습니다
- Package 파일에 Parchment 정보를 추가했습니다
|scrollable|fixed|
|---|---|
|![Screen Shot 2022-07-10 at 0 48 37](https://user-images.githubusercontent.com/39911797/178112968-d6d21152-fcf4-4dc6-811f-1cd95e4be85c.png)|![Screen Shot 2022-07-10 at 0 48 49](https://user-images.githubusercontent.com/39911797/178112979-f38388c8-c664-4883-93e6-b918d602d1f1.png)|
=> [#141] YDSTabBar 좌우 여백 추가

YDS/Source/Component/List/YDSList.swift
YDSList 내부 stackView의 spacing을 설정하는 코드가 두 줄 있어서 정리했습니다.
=> [#149] spacing 수정

YDS-Storybook/Resources/YDSTypographyArray.swift, YDS/Source/Foundation/YDSFont.swift, YDS/Source/Foundation/YDSTypoStyle.swift
새 Typo를 추가했습니다.
성적표에서 40, 32 크기의 Typo가 Display1과 Display2로 추가됐습니다.
- 이슈 티켓 : #151 
- 피그마 : [링크](https://www.figma.com/file/0u52cd50xDQqjanMpUvUOM/%5B1.-iOS%5D-Yourssu-Design-System?node-id=0%3A1) 
|display1|display2|
|---|---|
|<img width="564" alt="Screen Shot 2022-07-14 at 19 31 59" src="https://user-images.githubusercontent.com/39911797/178962866-4a3d136d-0bd8-4b3a-8ed5-93bd913be354.png">|<img width="564" alt="Screen Shot 2022-07-14 at 19 32 02" src="https://user-images.githubusercontent.com/39911797/178962914-ae8bc742-51b5-4c30-a9ca-c422a912eea1.png">
=> [#151] Typo 추가

YDS-Storybook/Storybook/ControllerView/Base/PickerControllerView.swift, YDS.xcodeproj/project.pbxproj, YDS.xcodeproj/xcshareddata/xcschemes/YDS-Storybook.xcscheme, YDS.xcodeproj/xcshareddata/xcschemes/YDS.xcscheme
빌드하고 나면 뜨는 Warning을 해결했습니다.
- 이슈 티켓 : #154 
- 동일한 Swift 파일을 여러 번 컴파일 되고 있어서 build phase를 수정했습니다.
- Warning이 뜨던 생성자 파라미터를 수정했습니다.
- Validate Project Settings를 Recommend setting이 되게 했습니다.
Clean 후 새로 build 해도 Warning이 안 뜨는 모습
=> [#154] Warning 해결하기

YDS-Storybook/AtomSampleViewController/LabelPageViewController.swift, YDS-Storybook/Extension/Description/NSTextAlignment+CustomStringConvertible.swift, YDS.xcodeproj/project.pbxproj, YDS/Source/Atom/YDSLabel.swift, YDS/Source/Foundation/YDSTypoStyle.swift
-  기본 정렬은 Left로 되어있다.
-  center, right, justified, natural 정렬도 할 수 있게 코드 추가하기
-  새로운 기능 추가하기
- 이슈 티켓 : https://github.com/yourssu/YDS-iOS/issues/175
- 피그마 : 
- 관련 문서 : 
https://user-images.githubusercontent.com/78733700/195771450-d0de2017-946f-41e9-85d1-379f62cc32ef.mp4
=> [#175] YDSLabel 다른 정렬 추가하기

YDS/Source/Atom/YDSTextField/YDSPasswordTextField/YDSPasswordTextField.swift, YDS/Source/Atom/YDSTextField/YDSSearchTextField.swift, YDS/Source/Atom/YDSTextField/YDSSimpleTextField/YDSSimpleTextField.swift, YDS/Source/Atom/YDSTextField/YDSSuffixTextField/YDSSuffixTextField.swift
YDS TextField Rounding을 적용하였습니다.
(SimpleTextFieldView, SuffixTextFieldView, PasswordTextFieldView, SearchTextField)
- 이슈 티켓 : https://github.com/yourssu/YDS-iOS/issues/181
- 피그마 : https://www.figma.com/file/0u52cd50xDQqjanMpUvUOM/%5B1.-iOS%5D-Yourssu-Design-System?node-id=1290%3A11669
- 관련 문서 : 
https://songios.tistory.com/43
https://user-images.githubusercontent.com/78733700/200507269-31023670-a263-4752-9eec-99e958a2619a.mp4
=> [#181] TextField Rounding 적용

YDS-Storybook/SwiftUI/PageListView.swift, YDS-SwiftUI/Source/Exported.swift, YDS-SwiftUI/Source/Foundation/YDSBasicColor.swift, YDS-SwiftUI/Source/Foundation/YDSIcon.swift, YDS.xcodeproj/project.pbxproj, YDS/Source/Exported.swift
AnyView로 되어있던 PageListView를 ViewBuilder으로 변경하였습니다.
AnyView는 권장되지 않는 방법이므로 변경하였습니다.
- 이슈 티켓 : #189 
- 피그마 : 
- 관련 문서 : 
https://github.com/yourssu/YDS-iOS/assets/19565940/fbaafbf6-6781-41fc-952e-7d2146fa0b5a
=> [#189] ViewBuilder으로 PageListView 개선

YDS-Storybook/SwiftUI/Resources/SwiftUIYDSColorArray.swift, YDS.xcodeproj/project.pbxproj
- SwiftUI용 ColorArrary 추가 했습니다.
- @chongin12 
Resources 파일에 Array로 넣어두었습니다.
- 이슈 티켓 : #197 
- 피그마 : 
- 관련 문서 :
=> [#197] SwiftUI용 ColorArray 데이터 추가

YDS-Storybook/SwiftUI/Foundation/ColorPageView.swift, YDS-Storybook/SwiftUI/PageListView.swift, YDS-Storybook/SwiftUI/Resources/SwiftUIYDSColorArray.swift, YDS-Storybook/UIKit/AtomSampleViewController/LabelPageViewController.swift, YDS-Storybook/UIKit/AtomSampleViewController/TextViewViewController.swift, YDS-Storybook/UIKit/FoundationSampleViewController/Color/ColorsListItemCell.swift, YDS-Storybook/UIKit/FoundationSampleViewController/Color/ColorsListTableViewController.swift, YDS-Storybook/UIKit/FoundationSampleViewController/Color/ColorsPageViewController.swift, YDS-Storybook/UIKit/Resources/YDSColorArray.swift
색깔 정보를 표현하는 뷰입니다.
- 이슈 티켓 : #200 
- 피그마 : 
- 관련 문서 : 
https://github.com/yourssu/YDS-iOS/assets/19565940/60668d85-5776-4012-b50c-33a0f9e29155
=> [feature] SwiftUI용 ColorPageView

YDS-Storybook/SwiftUI/Foundation/IconPageView.swift, YDS-Storybook/SwiftUI/PageListView.swift, YDS-Storybook/SwiftUI/Resources/SwiftUIYDSIconArray.swift, YDS-SwiftUI/Source/Foundation/YDSIcon.swift
아이콘 정보를 나타내는 뷰입니다.
- 이슈 티켓 : #196 
- 피그마 : 
- 관련 문서 : 
https://github.com/yourssu/YDS-iOS/assets/71203867/2d096f08-427d-4961-88e0-46c306ddae73
=> [feature] SwiftUI용 IconPageView

YDS-Storybook/SwiftUI/Foundation/TypoPageView.swift, YDS-Storybook/SwiftUI/PageListView.swift, YDS-Storybook/SwiftUI/Resources/SwiftUIYDSTypoArray.swift, YDS-Storybook/UIKit/FoundationSampleViewController/Typography/TypographiesListItemCell.swift, YDS.xcodeproj/project.pbxproj
Typography 정보를 표현하는 뷰입니다.
- 이슈 티켓 : #202 
- 피그마 : 
- 관련 문서 : 
https://github.com/yourssu/YDS-iOS/assets/84546438/09b40c02-a5e1-48d9-b088-327574394fa7
=> [#202] SwiftUI용 TypoPageView

YDS-Storybook/SwiftUI/Foundation/TypoPageView.swift
기존 코드에서 `SampleLabel.sampleLabel` 값이 없어서 main이 빌드가 되지 않았습니다.
따라서 `SampleText.sampleText`로 변경하려고 합니다.
- 이슈 티켓 : #207 
- 피그마 : 
- 관련 문서 :
=> [#207] SampleLabel 대신 SampleText 값으로 변경

YDS-Storybook/UIKit/FoundationSampleViewController/Typography/TypographiesListTableViewController.swift, YDS-Storybook/UIKit/FoundationSampleViewController/Typography/TypographiesPageViewController.swift
UITableView의 셀의 높이를 고정해서 셀마다 글자 넘치는 버그 해결했습니다.
- 이슈 티켓 : #212 
- 피그마 : 
- 관련 문서 : 
https://github.com/yourssu/YDS-iOS/assets/125457422/966971bd-8dce-4b5f-aa02-2e51055380ee
=> [#212] yds storybook Typo 버그

YDS-Storybook/SwiftUI/Atom/BoxButtonPageView.swift, YDS-Storybook/SwiftUI/Atom/PlainButtonPageView.swift, YDS-Storybook/SwiftUI/PageListView.swift, YDS-SwiftUI/Source/Atom/YDSBoxButton.swift, YDS-SwiftUI/Source/Atom/YDSPlainButton.swift, YDS.xcodeproj/project.pbxproj
SwiftUI에서 사용할 수 있는 YDSBoxButton, YDSPlainButton 구현 내용입니다.
- 이슈 티켓 : #225 
- 피그마 : 
- 관련 문서 : 
https://github.com/yourssu/YDS-iOS/assets/78733700/607a2802-7cef-454d-af02-86db334cd7fb
=> [#225] YDSButton 구현

YDS-Storybook/UIKit/AtomSampleViewController/ChipPageViewController.swift, YDS-Storybook/UIKit/PageListViewController.swift, YDS.xcodeproj/project.pbxproj, YDS/Source/Atom/YDSChip.swift
- UIKit 버전으로 Chip 구현하였습니다. 
- 이슈 티켓 : #227 
- 피그마 : 
- 관련 문서 : 
- Jasper님 SetNeeds.swift 코드에선 iOS 15이상부턴 `@Invalidating` 프로퍼티래퍼를 사용해달라고해서 일단
```swift
@SetNeeds(wrappedValue: nil, .layout)
```
대신에
```swift
@Invalidating(wrappedValue: nil, .layout)
```
로 구현했는데 같이 봐주시면 감사하겠습니다. 아마 다른 분들도 똑같을 것같아요!
https://developer.apple.com/documentation/uikit/uiview/invalidating
<figure class="half">
</figure>
=> [#227] UIKit Chip 구현

YDS-Storybook/SwiftUI/Component/BottomBarControllerPageView.swift, YDS-Storybook/SwiftUI/PageListView.swift, YDS-SwiftUI/Source/Component/YDSBottomBarController.swift, YDS.xcodeproj/project.pbxproj
YDSBottomBarController 구현하였습니다.
TabItem를 생성한 만큼 Tab이 만들어집니다.
- 이슈 티켓 : #231 
https://github.com/yourssu/YDS-iOS/assets/84546438/b3776ec2-84b6-4105-9bda-8d169b30772b
=> [#231] YDSBottomBarController 구현

YDS-Storybook/SwiftUI/Components/ListPageView.swift, YDS-Storybook/SwiftUI/PageListView.swift, YDS-SwiftUI/Source/Component/YDSList.swift, YDS-SwiftUI/Source/Component/YDSListItem.swift, YDS.xcodeproj/project.pbxproj
SwiftUI로 List를 구현했습니다.
- 이슈 티켓 : #221 
- 피그마 : 
- 관련 문서 : 
YDSList 에 subheaderHas를 옵셔널 타입으로, items 인자는 YDSListItem 배열로 수정하였습니다.
=> [#221] SwiftUI YDS List 구현

YDS-Storybook/SwiftUI/Atom/ChipPageView.swift, YDS-Storybook/SwiftUI/Atom/TextViewPageView.swift, YDS-Storybook/SwiftUI/PageListView.swift, YDS-SwiftUI/Source/Atom/YDSChip.swift, YDS.xcodeproj/project.pbxproj, YDS/Source/Atom/YDSChip.swift
오류때문에 다시 브랜치 세팅해서 옮겼습니다.
UIKit으로 제작된 YDSChip에도 SwiftLint 오류가 있어 같이 해결했습니다.
- 이슈 티켓 : #229 
- 피그마 : 
- 관련 문서 :
=> [#229-1] SwiftUI Chip 구현

Package.swift
안녕하세요. 
["쿠링"](https://github.com/ku-ring)이라는 건대생을 위한 공지알리미 앱서비스를 개발하는 동아리의 iOS 개발자 입니다!
학우들을 위한 서비스를 개발한다는 취지가 같아 좋은 레퍼런스가 되지 않을까 싶어서 깃헙을 구경하고 있습니다.
코드 보던 중 불필요한 인터페이스 사용이 보여서 수정하였습니다. 아주 작은 수정입니다.
그리고 만약 다들 Xcode15 이상 사용한다면 5.9 로 컴파일러 버전을 올려도 좋아보입니다.
응원합니다 🙌
- 이슈 티켓 : None
- 피그마 : None
- 관련 문서 : None
=> [수정] Package.swift- 불필요한 코드제거

YDS-Storybook/SwiftUI/Atom/ProfileImagePageView.swift, YDS-Storybook/SwiftUI/Storybook/CodeViewer.html, YDS-Storybook/SwiftUI/Storybook/StorybookPageView.swift, YDS.xcodeproj/project.pbxproj
- YDS Storybook을 보고 실제 코드가 어떻게 생겼는지, 구현하는지에 대해서 설명해주는 코드 뷰어가 있으면 좋겠다는 생각을 했습니다.
- 먼저 SwiftUI에서 code 영역이 있는 방식이 괜찮은지 한 번 확인해보기 위해서 PR을 올려보았습니다.
- 현재 구현 방식, 아이디어 모두 피드백 받을 수 있으면 좋겠습니다!
- 현재는 Text로만 이루어져있는데, 실제 Code Block을 보여준다던다, highlighting만 한다던지, 혹은 Bottomsheet로 보여주면 좋겠다던지 어떤 피드백이던지 환영합니다!
- 이슈 티켓 : #268 
- 피그마 : 
- 관련 문서 : 
- Code의 String 값이 어디에 있어야할지, 그리고 값을 PageView에 어떻게 넘겨줄지에 대해서 고민이 많았습니다.
- 상세 뷰에서 Code에 대한 State 변수로 String 값을 가지고 있고, 해당 값을 Binding으로 PageView에 값을 넘겨줍니다.
- 상세 뷰에서 PageView로 값을 올리려면 Binding으로 데이터를 넘겨주고 싶었는데, 상세 뷰에서 다른 State 값의 업데이트에 따라서 Code의 State 값이 업데이트 되는 것을 어떻게 구현할지에 대해서 고민이 많았습니다.
- onChange를 통해 State 변화를 감지하고, 변화한 경우에 Code 값을 업데이트하도록 변경하였습니다.
=> [#268] YDS 코드 뷰어
