YDS-Storybook/FoundationSampleViewController/Typography/TypographiesListItemCell.swift, YDS-Storybook/FoundationSampleViewController/Typography/TypographiesListTableViewController.swift, YDS-Storybook/FoundationSampleViewController/Typography/TypographiesPageViewController.swift, YDS-Storybook/PageListViewController.swift, YDS-Storybook/Resources/YDSTypographyArray.swift, YDS.xcodeproj/project.pbxproj, YDS/Source/Foundation/YDSTypoStyle.swift
YDS의 TypoStyle 정의 방법을 변경했습니다.
YDS-Storybook에 Typography 페이지를 작성했습니다.
https://user-images.githubusercontent.com/54972653/133208630-141c60a1-e19d-465f-9d0e-6e715687b3a6.mov
**TypoStyle** 
- font, lineHeight 값을 함수 외부에서 관리할 수 있도록 했습니다
- case 문을 중첩할 수 있어 관리가 편해집니다
**YDS/Source/Foundation/YDSTypoStyle.swift**
- font, lineHeight를 case문 외부로 꺼내 computed property로 관리하도록 했습니다
**YDS-Storybook/Resources/YDSTypographyArray.swift**
- YDS의 Typo 스타일을 담은 배열입니다
**YDS-Storybook/FoundationSampleViewController/Typography/TypographiesPageViewController.swift**
- Typography 페이지의 뷰 컨트롤러입니다
**YDS-Storybook/FoundationSampleViewController/Typography/TypographiesListTableViewController.swift**
- Typography를 보여주는 테이블 뷰 컨트롤러입니다
**YDS-Storybook/FoundationSampleViewController/Typography/TypographiesListItemCell.swift**
- …
=> [Feature/YDS-78] TypoStyle 정의 수정 및 Typography 페이지 작성

YDS/Source/Foundation/YDSTypoStyle.swift
line spacing 계산 공식을 수정합니다
좌 Before / 우 After
식을 잘못 써서 line spacing 속성이 전혀 적용되지 않고 있었습니다
- 이슈 티켓 : https://github.com/yourssu/YDS-iOS/issues/85
=> [#85] YDSLabel linespacing 버그 수정

YDS/Source/Component/TopBar/YDSNavigationController.swift
iOS 15에서 navigationbar 애니메이션이 정상 작동하지 않는 문제를 수정했습니다
iOS 13부터 도입된 [UINavigationBarAppearance](https://developer.apple.com/documentation/uikit/uinavigationbarappearance) 를 사용해야 iOS 15부터 화면 전환 애니메이션이 끊기지 않는 것으로 보입니다
이를 해결하기 위해 navigationBar 로 접근하던 속성 대부분을 변경했습니다
- 이슈 티켓 : https://github.com/yourssu/YDS-iOS/issues/82
- 슬랙에 올린 영상 : https://yourssu.slack.com/archives/CM8DWU3KP/p1632471592262700
[WWDC 영상(앞에 10분만 보면 됨)](https://developer.apple.com/videos/play/wwdc2019/224)
[한국어 블로그](https://zeddios.tistory.com/860)
=> [#82] navigationbar appearance 도입

YDS-Storybook/ComponentSampleViewController/TopBar/TopBarSampleViewController.swift, YDS/Source/Component/TopBar/YDSTopBarButton.swift
1. TopBarButton의 setTitle, setImage 함수를 오버라이딩 하여 이미지 속 밑줄 친 조건을 충족시켰습니다 
2. setTitle, setImage 함수로 버튼의 내용물을 바꿨을 때 pressed 컬러가 제대로 적용되도록 수정했습니다
1. 
setTitle과 setImage 함수를 오버라이딩 하기 전에는
TopBarButton에 이미지와 텍스트가 동시에 존재할 수가 있었습니다
이를 방지하기 위해 setTitle 함수가 작동될 때 Image가 있는지 없는지 미리 파악한 후
Image가 없을 경우에만 작동하도록 수정했습니다
setImage 함수 역시 마찬가지입니다
2.
UIControl.State는 normal, highlighted, disabled, selected, focused, application, reserved 등의 상태를 가지고 있는데
이들 상태는 배타적이지 않고 중복될 수 있습니다
이에 따라 selected이면서 highlighted인 상태가 발생하기도 하는데
이 경우엔 setTitleColor(fgPressedColor, for: .highlighted) 이런 식으로 컬러를 지정해주더라도 
`highlighted 상태`와 `highlighted 이면서 selected인 상태`는 서로 다른 상태이기 때문에 pressed 컬러가 제대로 지정되지 않습니다
이 문제를 해결하기 위해 TopBarButton 내부에서 isHighlighted 값에 따라서 titleColor를 지정하도록 코드를 수정했습니다
저도 뭐라고 설명해야 할지 이게 좀 난감하네요...
- 이슈 티켓 : …
=> [Feature/YDS-84] TopBarButton 아이콘, 글자 수정 가능하게 변경

YDS-Storybook/AtomSampleViewController/LabelPageViewController.swift, YDS-Storybook/PageListViewController.swift, YDS-Storybook/Storybook/ControllerView/IntControllerView.swift, YDS-Storybook/Storybook/StorybookPageViewController.swift, YDS.xcodeproj/project.pbxproj, YDS/Source/Atom/YDSLabel.swift, YDS/Source/Foundation/YDSTypoStyle.swift
YDSLabel이 lineBreakMode, lineBreakStrategy에 대응하도록 수정했습니다
Storybook에 YDSLabel 페이지를 추가했습니다
기존엔 lineBreakMode, lineBreakStrategy에 대응을 하지 않아서 외부에서 수정하려 해도 수정되지 않던 문제가 있었습니다.
이에 대응했습니다.
또한 Storybook에 YDSLabel을 사용해볼 수 있는 페이지도 추가했습니다.
- 이슈 티켓 : https://github.com/yourssu/YDS-iOS/issues/83
https://user-images.githubusercontent.com/54972653/142758728-b053f96e-928a-4668-9c6c-7c25e3e99138.mp4
https://user-images.githubusercontent.com/54972653/142758741-cc6aa6b3-2c26-4244-9aec-765fb83b4539.mp4
https://user-images.githubusercontent.com/54972653/142758755-76e74413-ede3-4e55-acc6-577a4f306d93.mp4
**- YDS/Source/Atom/YDSLabel.swift**
lineBreakMode, lineBreakStrategy에 대응하도록 수정했습니다
그 외 겸사겸사 생성자에 style의 기본 값을 설정했습니다 (이게 없어서 은근 쓰다보니까 불편하더라고요)
**- YDS/Source/Foundation/YDSTypoStyle.swift**
lineBreakMode, …
=> [Feature/YDS-83] YDSLabel 속성 대응 다양화 & 샘플 페이지 작성

YDS-Storybook/FoundationSampleViewController/Icon/IconsListItemCell.swift, YDS-Storybook/FoundationSampleViewController/Icon/IconsListTableViewController.swift, YDS-Storybook/FoundationSampleViewController/Icon/IconsPageViewController.swift, YDS-Storybook/PageListViewController.swift, YDS-Storybook/Resources/YDSIconArray.swift, YDS.xcodeproj/project.pbxproj, YDS/Source/Foundation/YDSIcon.swift
YDS에 추가한 아이콘을 확인할 수 있는 페이지뷰를 스토리북에 추가했습니다.
YDS 2.0.0으로 버전을 올리면서 기존 아이콘 스펙이 바꼈는데 아이콘 변경이 잘 이루어졌는지
디자이너들이 확인할 수 있게 하기 위해 스토리북에 아이콘 페이지뷰를 추가했습니다.
- 이슈 티켓 : #111 
- 피그마 : https://www.figma.com/file/yVXvVvBKZnG9BBsvdC3J5B/%5B0.-Common%5D-Yourssu-Design-System?node-id=1%3A462
- 관련 문서 : 
`ColorsPageViewController.swift`, `ColorsListTableViewController.swift`, `ColorsListItemCell.swift`를 참고했습니다.
https://user-images.githubusercontent.com/39911797/158056991-c773272a-617f-4787-b95a-de3ed645b730.mp4
=> [#111] 아이콘 페이지뷰 추가

YDS-Storybook/AppDelegate.swift, YDS-Storybook/Resources/YDSColorArray.swift, YDS/Source/Atom/YDSButton/YDSBoxButton.swift, YDS/Source/Component/YDSToast.swift, YDS/Source/Foundation/YDSSemanticColor.swift
1. Item을 제외하고 다크모드 컬러를 업데이트 했습니다
2. 겸사겸사 이름이 바뀐 컬러 ( ~~Reversed 가 ~~Bright 로 바뀜 )를 업데이트 해주고
3. 새로 생긴 컬러 (tooltip)를 추가해줬습니다
다크모드 도입 초창기이기 때문에 언제든 컬러는 바뀔 수 있습니다
- 이슈 티켓 : https://github.com/yourssu/YDS-iOS/issues/114
- 피그마 : https://www.figma.com/file/yVXvVvBKZnG9BBsvdC3J5B/%5B0.-Common%5D-Yourssu-Design-System?node-id=1%3A461
- 관련 문서 : 
- YDS/Source/Foundation/YDSSemanticColor.swift
- YDS-Storybook/Resources/YDSColorArray.swift
에서 피그마 상의 다크모드 컬러와 실제 코드에 적용된 다크모드 컬러가 동일한지 일일이 같이 확인해주신 후 어프루브를 눌러주세요
이 업데이트로 인해 기존에 ~~Reversed 라는 이름을 쓰던 컬러는 모두 ~~Bright 로 바뀌었습니다
따라서 YDS를 사용하는 프로젝트에서 ~~Reversed 컬러를 사용하고 있다면 빌드가 되지 않을 수 있습니다
이 업데이트가 적용된 이후엔 사용처에서 ~~Reversed 컬러를 ~~Bright 컬러로 바꿔주는 작업을 해야합니다
사실 deprecated 경고를 띄울 수도 있지만 YDS는 최신 버전 사용을 지향하는 게 원칙이라서 그냥 없애줍니다
벌써부터 레거시 만들면 귀찮아질지도...
기존 사용하던 코드에 지장이 생길 수 …
=> [#114] 다크모드 컬러 업데이트 (Item 제외)

YDS-Storybook/AtomSampleViewController/TextViewViewController.swift, YDS-Storybook/Extension/Optional+isEmpty.swift, YDS.xcodeproj/project.pbxproj, YDS/Source/Atom/YDSTextView.swift, YDS/Source/Extension/Optional+isEmpty.swift
ContentSize가 maxHeight를 넘어서 ScrollEnable이 되고난 후에,
Content를 지우면 다시 원래 사이즈로 돌아가지 않고 maxHeight를 유지해서
이를 수정했습니다.
TextView의 isScrollEnable가 true면 자동으로 사이즈 조절이 되지 않기 때문으로 보여서
intrinsicContentSize를 다시 계산하게 했습니다.
- 이슈 티켓 : Closes #117 
- 피그마 : 
- 관련 문서 : 
추가로 isShowingPlaceholder도 public으로 변경했습니다.
https://user-images.githubusercontent.com/19145853/158402400-d8f6dd3f-5928-4557-92cc-0448d46347ae.mp4
https://user-images.githubusercontent.com/19145853/158402415-aeb59c25-3424-4940-9592-d71ec329985e.mp4
=> [Fix/#117] YDS ContentSize 버그

YDS/Source/Atom/YDSEmojiButton.swift
기본 지정 색상을 설정합니다.
기존 스토리북배경 색상때문에 button의 기본 배경이 지정이되어 있지 않다는 사실을 몰랐습니다..ㅎ..ㅎ
- 이슈 티켓 :  #119 
- 피그마 : 
- 관련 문서 : 
#120  이전 PR 
배경색 바꾸고 테스트 했습니다!
=> [#119] EmojiButton 기본 배경색상 지정

YDS-Storybook/AppDelegate.swift, YDS-Storybook/Info.plist, YDS-Storybook/SceneDelegate.swift, YDS.xcodeproj/project.pbxproj, YDS/Source/Component/YDSToast.swift, YDS/Source/Extension/UIApplication+findWindow.swift
YDSToast Window를 찾는 방식을 수정했습니다.
Soomsil에서는 SceneDelegate를 사용해서
기존의 AppDelegate에서 window를 찾는방식이 아닌 SceneDelegate에서 찾는 방식으로 변경하였습니다.
- 이슈 티켓 : Closes #122 
- 피그마 : 
- 관련 문서 : 
[stackoverflow](https://stackoverflow.com/questions/57134259/how-to-resolve-keywindow-was-deprecated-in-ios-13-0)
https://user-images.githubusercontent.com/19145853/161374134-86c4bbb0-e90c-472f-971d-0e40bf992c2e.mp4
=> [#122] YDSToast Window 찾는 방식 수정

YDS-Storybook/ComponentSampleViewController/Tooltip/TooltipPageViewController.swift, YDS-Storybook/ComponentSampleViewController/Tooltip/TooltipSampleViewController.swift, YDS-Storybook/PageListViewController.swift, YDS.xcodeproj/project.pbxproj, YDS/Source/Component/YDSTooltip.swift
개발한 툴팁의 코드를 수정했습니다.
리뷰, 피드백을 반영해서 코드를 수정했습니다.
리베이스 풀을 잘못해서 브랜치가 꼬여서 새 브랜치에서 작업했습니다.
- 이슈 티켓 : #109
- 피그마 : https://www.figma.com/file/0u52cd50xDQqjanMpUvUOM/%5B1.-iOS%5D-Yourssu-Design-System?node-id=4227%3A2114
- 관련 문서 : [Tooltip 문서](https://yourssu.notion.site/Tooltip-5c208827cbfc41d696bf51e11b386afc), [YDSTooltip 문서](https://yourssu.notion.site/YDSTooltip-ded15e3556c84784ae784c0c8bb5f1e6), [이전 PR](https://github.com/yourssu/YDS-iOS/pull/124)
- `private var tailLayer: CAShapeLayer = CAShapeLayer()`로 꼬리 부분을 그리는 layer 변수를 관리
- `setProperties()`에서 `tailLayer`를 툴팁의 첫 번째 sublayer로 삽입
- `makeTail()`에서 `tailLayer`의 path, color를 변경
- 툴팁의 속성(text, color, tailPosition)이 바뀌면 `setNeedsLayout()`을 호출 (Layout Driven UI)
- `layoutSubviews()`에서 툴팁의 text, 배경색, 꼬리를 설정
- `private lazy var touchControl: …
=> [#109] YDSTooltip (리뷰 반영한 툴팁)

YDS/Source/Component/List/YDSListItem.swift, YDS/Source/Component/List/YDSListToggleItem.swift
listItem의 title을 가져올 수 있게 메소드를 추가했습니다.
여러개의 listItem이 있을 때 각각의 listItem을 구별하기 위한 수단으로 getTitle()을 추가했습니다.
- 이슈 티켓 : #136 
- 피그마 : 
- 관련 문서 :
=> [#136] ListItem의 title을 가져올 수 있도록 수정

YDS-Storybook/Resources/YDSIconArray.swift
새로 추가한 `xcircle_filled` 아이콘을 스토리북에서도 볼 수 있게 추가했습니다.
스토리북 코드도 수정해야 되는 걸 깜빡했어요...
- 이슈 티켓 : #143
=> [#143] YDSIconArray에 새 아이콘 추가

YDS-Storybook/AtomSampleViewController/TextViewViewController.swift
YDSTextView 스토리북 코드를 수정했습니다.
UIButton 대신 YDSPlainButton을 써야 해서 그 부분을 수정했습니다.
- 이슈 티켓 : #145 
- 피그마 : https://www.figma.com/file/p4lHNgQiXYr79ERh7w6jpM/Soomsil---iOS?node-id=3356%3A30750
|라이트모드|다크모드|
|---|---|
|![Screen Shot 2022-07-11 at 1 17 38](https://user-images.githubusercontent.com/39911797/178201974-82414723-e7b2-4c0e-ac3a-1574594ac054.png)|![Screen Shot 2022-07-11 at 1 17 40](https://user-images.githubusercontent.com/39911797/178202001-f817bb0a-d3a4-4ca3-b581-5789f6049266.png)|
=> [#145] YDSTextView 스토리북 코드 수정

YDS.xcodeproj/project.pbxproj, YDS/Source/SetNeedsLayout.swift
변수의 값이 변하면 자동으로 `setNeedsLayout()`을 호출하는 `property wrapper`를 추가했습니다.
YDS를 리팩토링하며 `Layout Driven UI`를 적용하고 코드 재사용성을 높이기 위해서입니다.
- 이슈 티켓 : #128 
- 사용하려면 `@SetNeedsLayout`를 변수 앞에 추가하면 됩니다.
- iOS 15부터 `@Invalidating` 이라는 property wrapper를 사용할 수 있는데 현재 YDS는 iOS 13부터 지원합니다.
- iOS 15로 버전을 올리게 되면 `@Invalidating`을 사용하게 `@available` 구문을 추가했습니다.
- `wrappedValue`는 쓰이지 않아서 접근을 막아놨습니다. 
- `subscript(_enclosingInstance:wrapped:storage:)` 구문을 통해 property wrapper 내부에서 외부의 `self`에 접근할 수 있습니다.
- [Layout Driven UI](https://www.sungdoo.dev/programming/layout-driven-ui/)
- [Swift Property Wrapper](https://docs.swift.org/swift-book/LanguageGuide/Properties.html#ID617)
- [UIView.Invalidating](https://developer.apple.com/documentation/uikit/uiview/invalidating)
- [Referencing the enclosing 'self' in a wrapper …
=> [#128]-1 SetNeedsLayout Property Wrapper 추가

YDS-Storybook/Storybook/ControllerView/Base/PickerControllerView.swift
피커뷰에서 done 버튼을 눌렀을 때 앱이 튕기던 버그를 해결했습니다.
피커뷰 위에 추가한 툴바의 done 버튼이 올바르게 작동되기 위해서는 `target`을 `self`로 해야 되는데
warning이 뜨고 있어서 Xcode에서 제안한 방법으로 고쳤다가 버그가 생겼습니다.
- 이슈 티켓 : #156 
툴바 버튼의 `target`을 다시 `self`로 바꿨습니다.
다시 생긴 warning은 `let`에서 `lazy var`로 바꾸는 방법으로 해결했습니다.
툴바가 let으로 선언된 상태일 때는 self가 존재하지 않아서 warning이 뜨는데
lazy var로 수정하면 이 변수에 대한 참조가 이루어질 때, 변수가 생성되는데
이러한 연산이 실행될 때는 self가 존재해서 접근할 수 있기 때문에 warning이 사라집니다.
[Swift 5.6 warning on self](https://samwize.com/2022/03/21/swift-5-6-warning-on-self/)
https://user-images.githubusercontent.com/39911797/183298593-22322937-0f9a-486a-9c41-272cb8dd8027.mp4
=> [#156] 피커뷰에서 done 버튼 눌렀을 때 튕기던 버그 해결

YDS/Source/Foundation/YDSTypoStyle.swift
Button류 typo별 lineHeight를 수정했습니다.
크기가 작을 때 문자열 잘림 현상이 있어서 수정된 lineHeight 수치를 반영했습니다.
- 이슈 티켓 : #157 
- 피그마 : [링크](https://www.figma.com/embed?embed_host=share&url=https%3A%2F%2Fwww.figma.com%2Ffile%2F0u52cd50xDQqjanMpUvUOM%2F%255B1.-iOS%255D-Yourssu-Design-System%3Fnode-id%3D2%253A53)
- 관련 문서 : [노션](https://www.notion.so/yourssu/IOS-Typo-Button-line-height-ca2c723db75b48e3899bbc221b0ae66a)
=> [#157] 폰트 lineHeight 수정

YDS-Storybook/AtomSampleViewController/LabelPageViewController.swift, YDS-Storybook/AtomSampleViewController/TextViewViewController.swift, YDS-Storybook/Extension/Description/NSLineBreakMode+CustomStringConvertible.swift, YDS-Storybook/Extension/Description/NSParagraphStyle.LineBreakStrategy+CustomStringConvertible.swift, YDS-Storybook/Extension/Description/UIModalPresentationStyle+CustomStringConvertible.swift, YDS-Storybook/Resources/YDSColorArray.swift, YDS.xcodeproj/project.pbxproj, YDS/Source/Atom/YDSTextView.swift
- 굳이 layoutSubviews에서 할 필요가 없어 보이는 작업을 따로 뺐습니다.
- 추가적으로 picker item에서 NS관련객체나 custom 객체에서 이름이 불명확하거나 어렵게 되어 있는 것을 실제 케이스에 맞게CustomStringConvertible을 구현했습니다.
> layoutSubviews 다이어트
- placeholder가 등록되고 변경될 때만 수정, 등록이 일어나는게 맞고, layout이 바뀔 때랑은 관련이 없다고 판단해서 해당 로직은 placehodler의 didSet으로 옮겼습니다.
- text가 변해서 TextView의 크기를 변화시킬 때는 시스템이 layoutSubviews가 불러주기 때문에, 굳이 text에 SetNeeds는 필요는 없을 듯합니다.
- 대신 전처럼 textDidChange로 placeholder가 보여줄지 말지만 호출하도록 했습니다.
- style역시, lineBreak 등은 ContentSize를 변경할 수 있어 layout변화가 있지만, 이 역시 시스템이 자동으로 layoutSubviews를 불러주기때문에 굳이 SetNeedsLayout를 호출할 필요는 없어보입니다 
- didSet에서 스타일 변화만 attributedText에 적용했습니다.
- textColor도 layout과 상관없을 것 같아 제거하고 , textColor만 바꾸는 함수를 만들었습니다.
- placeholderColor도 layout과 상관없을 것 같아 제거했습니다.
기존에 style 변경이 typingAttributes를 변경했었는데 이는 newly typed text에만 적용되는거라 …
=> [Fix/#163] YDSTextView layoutSubviews의 책임을 줄였습니다.

YDS/Source/Component/YDSBottomBarController.swift
BottomBar의 외관을 설정하는 과정에서 scrollEdgeAppearance를 설정해주지 않아
iOS 15 이상에서 'scrollEdge' 상황에 #000000 인 썡 검정 컬러가 나타나는 문제가 있었습니다
이 문제를 해결하고, 동시에 잘못 짜여진 코드를 수정합니다
- 이슈 티켓 : https://github.com/yourssu/YDS-iOS/issues/171
- 관련 문서 : [UITabBarAppearance 문서](https://developer.apple.com/documentation/uikit/uitabbarappearance)
https://user-images.githubusercontent.com/54972653/192150301-465c67de-0713-462a-b133-d1ef9bf34d0f.mp4
https://user-images.githubusercontent.com/54972653/192150309-b202bbf6-d3ca-4458-af4a-d835f6aeedc8.mp4
iOS 13 이후부터 UIBarAppearance 라는 개념이 추가되었습니다
UINavigationBar, UITabBar 등의 외관 설정을 모아두는 객체라고 생각하면 됩니다
UIBarAppearance 객체를 통해서 설정된 상태는 기존의 방식으로 설정한 것보다 높은 우선순위를 가집니다
- eg) appearance.backgroundColor 의 우선순위가 tabBar.background 보다 높습니다
UIBarAppearance를 이용해 standardAppearance, …
=> [#171] BottomBar의 scrollEdgeAppearance 미지원 문제 해결 및 코드 정리

YDS-Storybook/AtomSampleViewController/LabelPageViewController.swift
- YDSLable에서 짧은 단어일 때 alignment가 적용 안돼서 autoLayout 수정했습니다.
- alignment의 default option 값도 `center`로 수정하였습니다.
=> 기존의 레이아웃은 텍스트가 입력된 크기만큼만(첫 번째 사진 참고) 레이아웃이 잡혀서 아무리 alignment를 수정해도 짧은 단어일 때는 정렬이 되지 않습니다. 그래서 텍스트가 보이는 뷰의 레이아웃을 다시 수정해주었습니다. (두 번째 사진 참고)
- 이슈 티켓 : https://github.com/yourssu/YDS-iOS/issues/183
- 피그마 : 
- 관련 문서 : 
https://user-images.githubusercontent.com/78733700/205230935-31111cc9-1ac0-43eb-8a9c-042ef19fbe4b.mp4
=> [#183] YDSLabel autoLayout 수정하기

YDS-Storybook/SwiftUI/Atom/ProfileImagePageView.swift, YDS-Storybook/SwiftUI/PageListView.swift, YDS-Storybook/SwiftUI/Resources/SwiftUIYDSImageArray.swift, YDS-Storybook/SwiftUI/Resources/YDSProfileImageView.swift, YDS-Storybook/SwiftUI/Storybook/OptionView/Base/Option.swift, YDS-Storybook/SwiftUI/Storybook/OptionView/OptionalIconOptionView.swift, YDS-Storybook/SwiftUI/Storybook/OptionView/OptionalImageOptionView.swift, YDS-Storybook/SwiftUI/Storybook/StorybookPageView.swift, YDS.xcodeproj/project.pbxproj
- 기존에 작업했던 Option에 `OptionalImageOptionView`를 추가하여, Icon이 아닌 이미지를 추가하는 방식에 대한 `Option`도 추가하였습니다.
- ProfileImagePageView를 구현하였습니다.
- 이슈 티켓 : #206 
- 피그마 : 
- 관련 문서 : 
- 옵션에 Image를 적용할 수 없어서 일단 ImageArray를 추가하여 포팅할 수 있는 방식으로 사용하였습니다. -> 
- 현재 YDS SwiftUI에는 ProfileImage에 대한 컴포넌트가 없어서 해당 부분을 구현하기 위한 코드가 Storybook에 포함되어 있습니다. 이 부분 참고하시면 좋을 것 같아요. -> YDS_SwiftUI에 ProfileImageView 컴포넌트 제작 완료하였습니다.
- ProfileImage에서 바꿀 옵션을 줄 만한 부분이 Border로 보여서, Border Width와 Color를 수정할 수 있는 border 함수를 추가하도록 만들었습니다. 참고해주세요!
https://github.com/yourssu/YDS-iOS/assets/96258104/f84092b3-e557-4f00-a74b-b0a0e911ab0a
=> [#206] YDS Storybook SwiftUI용 ProfileImageView

YDS-Storybook/SwiftUI/Atom/LabelPageView.swift, YDS-SwiftUI/Source/Atom/YDSLabel.swift
- Label이 최대 크기로 설정되어, 다른 뷰를 잡아먹는 버그를 발견하였습니다.
- 하지만 값으로 지정하면 여러 줄이 들어오는 경우, 뷰가 짤릴 가능성이 있습니다.
- 그래서 동적으로 지정될 수 있도록 고민하였습니다.
- 이슈 티켓 : #223 
- 피그마 : 
- 관련 문서 : 
- 크기를 지정하지 않고 동적으로 알맞게 설정할 수 있도록 하기 위해서 방법을 고민했습니다.
https://stackoverflow.com/questions/56665048/how-do-i-make-my-swiftui-uiviewrepresentable-respect-intrinsiccontentsize-in-pre
https://stackoverflow.com/questions/68719533/how-do-i-change-the-height-of-this-uiviewrepresentable
=> [#223] Priority 설정으로 Label이 intrinsic하게 적용되도록 변경

YDS-Storybook/SwiftUI/Storybook/OptionView/BoolOptionView.swift
```swift
struct BoolOptionView: View {
private enum Dimension {
enum Spacing {
static let vstack: CGFloat = 8
static let textSpacing: CGFloat = 4
}
}
@Binding private var isOn: Bool
private let description: String?
init(description: String?, isOn: Binding<Bool>) {
self.description = description
self._isOn = isOn
}
var body: some View {
VStack(alignment: .leading, spacing: Dimension.Spacing.vstack) {
VStack(alignment: .leading, spacing: Dimension.Spacing.textSpacing) {
if let description = description {
Text(description)
.font(YDSFont.subtitle2)
}
Text("Bool")
.font(YDSFont.body2)
}
Toggle("", isOn: $isOn)
.labelsHidden()
}
}
}
```
SwiftUI용 StorybookPage의 toggle버튼에 Tint 색상이 적용안된 부분을 수정했습니다
- 이슈 티켓 : #236 
- 피그마 : 
- 관련 문서 :
=> [#236] StorybookPage toggle Tint적용

YDS-Storybook/SwiftUI/Atom/TextField/PasswordTextFieldPageView.swift, YDS-Storybook/SwiftUI/Atom/TextField/SearchTextFieldPageView.swift, YDS-Storybook/SwiftUI/Atom/TextField/SimpleTextFieldPageView.swift, YDS-Storybook/SwiftUI/Atom/TextField/SuffixTextFieldPageView.swift, YDS-Storybook/SwiftUI/PageListView.swift, YDS-Storybook/SwiftUI/Storybook/StorybookPageView.swift, YDS-SwiftUI/Source/Atom/YDSTextField/YDSPasswordTextField.swift, YDS-SwiftUI/Source/Atom/YDSTextField/YDSSearchTextField.swift, YDS-SwiftUI/Source/Atom/YDSTextField/YDSSimpleTextField.swift, YDS-SwiftUI/Source/Atom/YDSTextField/YDSSuffixTextField.swift, YDS-SwiftUI/Source/Atom/YDSTextField/YDSTextFieldBase.swift, YDS-SwiftUI/Source/Atom/YDSTextField/YDSTextFieldProtocol.swift, YDS.xcodeproj/project.pbxproj
- SwiftUI에서 사용 가능한 TextField 시리즈를 구현하였습니다.
- 이슈 티켓 : #218 
- 피그마 : 
- 관련 문서 : 
- TextField의 기본적인 뷰를 추가하기 위해서 Protocol을 작성했는데, 이런식으로 작성하는게 올바를지 같이 얘기해보면 좋을 것 같아요.
- TextField의 Base를 만들어서 각 TextField에서 해당 뷰에 필요한 값만을 넣어주는 형태로 작성했는데 괜찮을지 확인해주세요.
- Base에서는 leading과 trailing에 다양한 타입을 넣어주기 위해서 AnyView를 넣어주고, 각 TextField들에서 AnyView로 래핑해서 보여주는데 어떨지 의견을 공유하면 좋을 것 같아요.
-
=> [#218] YDS TextField 구현

README.md, YDS.xcodeproj/project.pbxproj
README에 이전 웹 YDS 주소가 들어가 있던 것을 최신화 하였습니다.
Package.swift를 수정하여 CI/CD 버그를 고쳐보고자 합니다.
- 이슈 티켓 : #244 
- 피그마 : 
- 관련 문서 : 
CI/CD 버그 : 
```
CFBundleIdentifier Collision. There is more than one bundle with the CFBundleIdentifier value 'com.yourssu.YDS-Essential' under the iOS application 'YDS-Storybook.app'
```
YDS와 YDS-SwiftUI에 들어있는 bundle identifier가 겹친다는 에러입니다.
YDS-Storybook : YDS, YDS-SwiftUI, YDS-Essential 모두를 embed
YDS : YDS-Essential에 대해 Do not Embed
YDS-SwiftUI : YDS-Essential에 대해 Do not Embed
=> [#244] README 업데이트 및 CI/CD 관련 Package.swift 파일 수정

YDS-Essential/Source/HapticManager.swift, YDS-Storybook/SwiftUI/Components/ToastPageView.swift, YDS-SwiftUI/Source/Component/YDSToast.swift, YDS.xcodeproj/project.pbxproj
Toast의 Duration이 먹히지 않던 버그를 수정하고, 햅틱 효과를 추가하였습니다.
- 이슈 티켓 : #249 
- 피그마 : 
- 관련 문서 : 
https://github.com/yourssu/YDS-iOS/assets/19565940/9a43f092-0849-4787-987d-1a6304e8ffb7
=> [#249] Toast Duration 수정 및 Haptic 추가

YDS-SwiftUI/Source/Foundation/YDSSemanticColor.swift
dark mode color 버그 수정했습니다.
아직은 SwiftUI에서 Color 자체를 dynamic으로 설정하는 기능이 없어보입니다.
추후 Mac이나 다른 프레임워크를 지원할 때 해당 프레임워크의 dynamic provider를 사용하면 될 것 같습니다.
- 이슈 티켓 : #254 
- 피그마 : 
- 관련 문서 : 
https://github.com/yourssu/YDS-iOS/assets/19565940/a3eb9081-d0d6-440a-8c4e-52516b75376a
=> [#254] dark mode color 버그 수정

YDS-Storybook/SwiftUI/Atom/LabelPageView.swift, YDS-Storybook/SwiftUI/Atom/TextViewPageView.swift, YDS-Storybook/SwiftUI/PageListView.swift, YDS-SwiftUI/Source/Atom/YDSLabel.swift, YDS-SwiftUI/Source/Atom/YDSTextView.swift, YDS-SwiftUI/Source/Foundation/YDSTypoStyle.swift, YDS.xcodeproj/project.pbxproj
SwiftUI용 TextView 구현
UIRepresentable 을 이용해 개발하다가 한계점을 깨닫고 SwiftUI의 TextEditor를 사용하여 YDSTextView를 구현하였습니다.
인자에는 textColor, placeholderText, placeholderTextColor, style, multilineTextAlignment, multilineTextAlignment, minHeight, maxHeight가 있습니다.
SwiftUI에서는 Font 사이즈를 측정하는 방법이 없기에 글자 크기에 맞는 TextEditor의 높이를 자동으로 설정해주지 못해 인자 중에 style과 minHeight는 필수로  사용자가 크기에 맞게 인자로 넣어줘야 합니다. 
그리고 TextEditor에는 제공되는 placeholder가 없어 직접 Text를 띄워 만들어주었습니다. 더 좋은 방법이 있다면 알려주세요.
또한 옵션으로는 multilineTextAlignment가 추가되었고, SwiftUI TextEditor에는 사용이 불가능한 NSlinebreakmode는 추가하지 않았습니다.
현재 발생하는 버그는 하나 있습니다. maxHeight를 설정해줬을때 TextEditor의 크기는 알맞게 최대 사이즈가 설정되지만 그 안에 들어가는 입력 값의 맨 마지막 줄 까지 스크롤이 되지 않는 버그입니다. 고치려고 해봤지만 잘 되지 않아요. 도움을 주세요..ㅜㅜ
- 이슈 티켓 : 
- 피그마 : 
- 관련 문서 : 
https://github.com/yourssu/YDS-iOS/assets/103497527/522f4280-da95- …
=> [#255] SwiftUI용 TextView 구현

YDS-Storybook/SwiftUI/Atom/BadgePageView.swift, YDS-Storybook/SwiftUI/Atom/EmojiButtonPageView.swift, YDS-Storybook/SwiftUI/Storybook/StorybookPageView.swift
StorybookPageView 내의 샘플 화면의 배경색을 수정했습니다(Color.white -> YDSColor.monoItemBG).
일부 Lint 문제를 해결했습니다.
- 이슈 티켓 : #258
- 피그마 : 
- 관련 문서 : 
간단하게 샘플 화면의 배경색을 수정한 PR입니다.
<STRIKE>일부 배경색을 수정한 화면에는 적용되지 않았습니다(EmojiButton, BadgeView). 이 부분의 수정도 현재 브랜치에 포함되야 할 내용일까요?</STRIKE>
BadgePageView에서 배경색을 UIKit과 동일하게 bgNormal로 수정했고,
EmojiButtonPageView에서 배경색을 삭제해서 다크모드 대응을 했습니다.
=> [#258] SwiftUI StorybookPageView 다크모드 대응

YDS-Storybook/SwiftUI/Atom/BottomSheetPageView.swift, YDS-Storybook/SwiftUI/PageListView.swift, YDS-SwiftUI/Source/Atom/YDSBottomSheet.swift, YDS.xcodeproj/project.pbxproj
SwiftUI로 Bottom Sheet를 구현했습니다
- 이슈 티켓 : #226
- 피그마 : 
- 관련 문서 : 
먼저, SwiftUI의 sheet를 활용해서 현재 디자인과 동일한 Bottom Sheet를 구현하기에 어려운 점이 있었습니다.
단순하게 높이 조절을 하는 presentationDetents()의 경우, iOS 16.0에서 사용이 가능하지만,
배경을 바꾸는 .presentationBackground, cornerRadius를 수정하는 .presentationCornerRadius()의 경우, iOS 16.4부터 대응이 되어 있어, 현재 16.0이 최소 버전인 프로젝트에서 사용할 수 없었습니다.
UIKit과 디자인을 같게 하기 위해, ZStack과 DragGesture를 활용해서 비슷하게 구현을 했지만, sheet 내의 뷰가 미리 로딩이 되어 있는 점, 현재 Storybook처럼 Tabbar가 있을 경우, 대응이 안된다는 문제가 있습니다.
SwiftUI를 활용한 다른 방식으로 구현해도 비슷한 문제가 있고, UIKit으로 구현하면 SwiftUI를 쓰는게 의미가 없어지는 것 같아, 어떻게 처리하면 좋을까요? 
https://developer.apple.com/documentation/swiftui/view/presentationbackground(alignment:content:)
https://developer.apple.com/documentation/swiftui/view/presentationcornerradius(_:)
=> [#226] YDS Bottom Sheet 구현

YDS-Storybook/SwiftUI/Atom/LabelPageView.swift, YDS-Storybook/SwiftUI/Storybook/OptionView/Base/Option.swift, YDS-Storybook/SwiftUI/Storybook/OptionView/OptionalIntOptionView.swift, YDS-Storybook/SwiftUI/Storybook/OptionView/OptionalStringOptionView.swift, YDS-Storybook/SwiftUI/Storybook/StorybookPageView.swift, YDS-SwiftUI/Source/Atom/YDSLabel.swift, YDS-SwiftUI/Source/Atom/YDSTextField/YDSTextFieldBase.swift, YDS-SwiftUI/Source/Foundation/YDSTypoStyle.swift, YDS.xcodeproj/project.pbxproj
1. 기존 UIKit 요소들을 없애고 **SwiftUI**에 정의된 속성 중 최대한 유사한 속성으로 교체해주었습니다.
- numberOfLines -> `lineLimits`
- textAlignment -> `multilineTextAlignment`
- lineBreakMode, lineBreakStrategy -> `truncationMode`, `allowsTightening`
2. 모든 속성을 설정하지 않고도 원하는 속성만 골라 적용할 수 있습니다.
- 설정하지 않은 속성은 기본값으로 적용됩니다.
3. UIKit에서의 numberOfLines = `0`은 SwiftUI에서의 lineLimits = `nil`과 같아 
lineLimits의 기본값을 nil로 설정하기 위해 `IntOptionView`를 `OptionalIntOptionView`로 수정하였습니다.
4. StorybookPageView의 backgroundColor를 기존 스토리북과 동일하게 변경하였습니다.
5. OptionalStringOptionView의 toggle이 false일 때의 placeholder의 색상(foregroundColor)을 변경하였습니다.
- 이슈 티켓 : #250 
- 피그마 : 
- 관련 문서 : 
[Simulator Screen Recording - iPhone 15 Pro - 2024-01-16 at 03.56.30.mp4.zip](https://github.com/yourssu/YDS-iOS/files/13942246/Simulator.Screen.Recording.-.iPhone.15.Pro.-.2024 …
=> [#255] YDSLabel SwiftUI로 리팩토링

YDS-Storybook/SwiftUI/Atom/BadgePageView.swift, YDS-Storybook/SwiftUI/Atom/BoxButtonPageView.swift, YDS-Storybook/SwiftUI/Atom/PlainButtonPageView.swift, YDS-Storybook/SwiftUI/Storybook/OptionView/Base/Option.swift, YDS-Storybook/SwiftUI/Storybook/OptionView/OptionalIconOptionView.swift, YDS-Storybook/SwiftUI/Storybook/StorybookPageView.swift, YDS-SwiftUI/Source/Atom/YDSBoxButton.swift, YDS-SwiftUI/Source/Atom/YDSPlainButton.swift
- SwiftUI PlainButton, BoxButton default 아이콘 변경
- SwiftUI PlainButton medium 옵션 수정
- button action 추가 가능하게 만들기
- 이슈 티켓 : #251 
- 피그마 : 
- 관련 문서 : 
앞으로 BoxButton이나 PlainButton에 Click Event 추가하시려면 아래와 같은 코드로 사용하시면 됩니다!
```swift
YDSBoxButton(
text: text,
leftIcon: leftIcon?.icon,
rightIcon: rightIcon?.icon,
type: YDSBoxButton.BoxButtonType.allCases[typeSelectedIndex],
size: YDSBoxButton.BoxButtonSize.allCases[sizeSelectedIndex],
rounding: YDSBoxButton.BoxButtonRounding.allCases[roundingSelectedIndex],
isDisabled: isDisabled,
isWarned: isWarned,
action: {
print("This is YDSBoxButton.")
})
```
https://github.com/yourssu/YDS-iOS/assets/78733700/4d6805cb-249e-40d2-9b3f-d2089566b714
=> [#251] SwiftUI BoxButton, PlainButton 수정

YDS-Storybook/SwiftUI/Atom/TextViewPageView.swift
현재 YDSPlainButton이 들어간 TextViewPageView에서 action이 없어 생기던 오류를 수정했습니다.
- 이슈 티켓 : #262 
- 피그마 : 
- 관련 문서 :
=> [#262] YDSButton이 들어간 뷰 액션 수정
